### ISSUE TITLE
Search Bar (not a bug, just could be optimized) priority->low

### ISSUE THREAD

**Issue by JalenYes** [Plaxy-Technologies-Inc/YouPlanets-Bug-Report#5]
**Describe the bug**
Searching Space on the search bar, cannot get SpaceX Club planet (Pic 1). Searching space on the search bar, can get SpaceX Club planet (Pic 2).  

**Screenshots**
<img width="517" alt="image" src="https://user-images.githubusercontent.com/40333215/101955757-62176680-3bcc-11eb-9b9d-1eaac1199a95.png">

<img width="567" alt="image" src="https://user-images.githubusercontent.com/40333215/101955933-b4f11e00-3bcc-11eb-8cea-990a8b32811c.png">

**Comment by JalenYes** [comment]
The difference is the lowercase or uppercase.

**Comment by kaichunwu** [comment]
should be fixed with Node PR#100

**Comment by JalenYes** [comment]
Now, nothing shows when searching space, spa, or planeter name (JalenYes in this case).  previously, this all works.

**Comment by kaichunwu** [comment]
sorry, that content is not updated because of the wrong index or you can think it as database.
the way you can solve it is update that planet name or description or anything in planet setting studio. after that, it will work

**Comment by JalenYes** [comment]
Thank you for letting me know! however, searching Space still cannot get spaceXship.  You can prioritize Notification instead of this. once you have time, pls take some time to optimize this. I'll close this issue for now.
